### ISSUE TITLE
Color display not working

### ISSUE THREAD

**Issue by bcbnz** [bcbnz/watchless#2]
With the command

```
./watchless.py -c ls -lh /usr/bin/ --color
```

the following traceback occurs:

```
Traceback (most recent call last):
  File "./watchless.py", line 671, in <module>
    curses.wrapper(wl.run)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./watchless.py", line 573, in run
    linelen, pieces = self.process_escape_codes(line)
  File "./watchless.py", line 480, in process_escape_codes
    code, text = chunk.split('m', 1)
ValueError: need more than 1 value to unpack
```

Running without the `-c` options shows an escape at the end of each line (probably resetting the display). Maybe the one on the very last line is causing this since there is no text following it?

**Comment by bcbnz** [comment]
Or maybe not? 

```
./watchless.py -c "ls -lh /usr/bin/ --color && echo foo"
```

Still has the error even though there is plain text to end the output.

**Comment by bcbnz** [comment]
Heh. So the colour code hadn't been committed to Github anyway...

Fixed, was the `[K` ANSI escape (clear to end of line) which was tripping up the parser which was only expecting colour codes to come through. Might need to make a more robust parser but this bug is closed for now.
